In [2]:
import torch
from torch.nn import MSELoss #Class

In [ ]:
yhat = torch.randn(size=(50,),dtype=torch.float32)
y = torch.randn(size=(50,),dtype=torch.float32)

In [1]:
criterion /loss

NameError: ignored

In [ ]:
criterion = MSELoss(reduction = "sum")

In [ ]:
loss = criterion(yhat,y)

In [ ]:
loss

tensor(89.0168)

In [ ]:
MSEloss(reduction = "mean"/"sum") #MSE #SSE

In [ ]:
import torch

In [ ]:
#loss = -(y*ln(sigma) + (1-y)*ln(1-sigma))

In [ ]:
#y - 真实标签
#sigma - sigmoid(z)
#z = Xw
#X , w
#m 样本量

In [ ]:
m = 3*pow(10,3)

torch.random.manual_seed(420)
X = torch.rand((m,4),dtype=torch.float32)
w = torch.rand((4,1),dtype=torch.float32)
y = torch.randint(low=0,high=2,size=(m,1),dtype=torch.float32)
zhat = torch.mm(X,w)
sigma = torch.sigmoid(zhat)

In [ ]:
sigma.shape

In [ ]:
#loss = -(y*ln(sigma) + (1-y)*ln(1-sigma))

In [ ]:
loss = -(1/m)*sum(y*torch.log(sigma) + (1-y)*torch.log(1-sigma))

In [ ]:
#total loss

In [ ]:
loss

tensor([0.7962])

In [ ]:
import time

In [ ]:
m = 3*pow(10,3)

In [ ]:
X = torch.rand((m,4),dtype=torch.float32)
w = torch.rand((4,1),dtype=torch.float32)
y = torch.randint(low=0,high=2,size=(m,1),dtype=torch.float32)
zhat = torch.mm(X,w)
sigma = torch.sigmoid(zhat)

In [ ]:
X.shape

torch.Size([3000, 4])

In [ ]:
start = time.time() #捕获现在的时间
loss1 = -(1/m)*sum(y*torch.log(sigma) + (1-y)*torch.log(1-sigma))
now = time.time() #以秒计
print(now - start)

0.051853179931640625


In [ ]:
start = time.time()
loss2 = -(1/m)*torch.sum(y*torch.log(sigma) + (1-y)*torch.log(1-sigma))
now = time.time() #以秒计
print(now - start)

0.000997304916381836


In [ ]:
import torch.nn as nn

In [ ]:
criterion = nn.BCELoss(reduction = "mean") #实例化
loss = criterion(sigma,y)

In [ ]:
loss

tensor(0.8951)

In [ ]:
criterion2 = nn.BCEWithLogitsLoss(reduction = "sum")

In [ ]:
loss = criterion2(zhat, y)

In [ ]:
loss

tensor(2685.3774)

In [ ]:
criterion2 = nn.BCEWithLogitsLoss(reduction = "none")

In [ ]:
loss = criterion2(zhat, y)

In [ ]:
loss.shape

torch.Size([3000, 1])

In [3]:
import torch
import torch.nn as nn

In [4]:
m = 3*pow(10,3)

In [5]:
torch.random.manual_seed(420)
X = torch.rand((m,4),dtype=torch.float32)
w = torch.rand((4,3),dtype=torch.float32)
y = torch.randint(low=0,high=3,size=(m,),dtype=torch.float32)

In [6]:
zhat = torch.mm(X,w)

In [ ]:
#sigma = torch.softmax(zhat)

In [ ]:
#logsoftmax - log + softmax, 输入:zhat

In [ ]:
#NLLLoss()

In [7]:
logsm = nn.LogSoftmax(dim=1)

In [8]:
logsigma = logsm(zhat)

In [9]:
logsigma

tensor([[-1.1139, -0.8802, -1.3585],
        [-1.0558, -0.8982, -1.4075],
        [-1.0920, -1.0626, -1.1430],
        ...,
        [-1.0519, -0.9180, -1.3805],
        [-1.0945, -1.1219, -1.0798],
        [-1.0276, -0.8891, -1.4649]])

In [10]:
criterion = nn.NLLLoss()

In [11]:
y

tensor([2., 2., 2.,  ..., 2., 2., 2.])

In [12]:
logsigma

tensor([[-1.1139, -0.8802, -1.3585],
        [-1.0558, -0.8982, -1.4075],
        [-1.0920, -1.0626, -1.1430],
        ...,
        [-1.0519, -0.9180, -1.3805],
        [-1.0945, -1.1219, -1.0798],
        [-1.0276, -0.8891, -1.4649]])

In [13]:
criterion(logsigma, y.long())

tensor(1.1147)

In [14]:
zhat

tensor([[0.9466, 1.1803, 0.7020],
        [1.1502, 1.3079, 0.7986],
        [0.5279, 0.5573, 0.4769],
        ...,
        [0.9136, 1.0475, 0.5850],
        [0.8667, 0.8393, 0.8814],
        [1.0314, 1.1700, 0.5941]])

In [ ]:
criterion = nn.CrossEntropyLoss()

In [ ]:
criterion(zhat,y.long())

tensor(1.1147)